spring:
  application:
    name: seckill-provider
  datasource:
    url: jdbc:mysql://localhost:3306/db_seckill?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 1021
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    port: 6379
    host: 127.0.0.1
    timeout: 3
    # 最大连接数 total idle wait
    jedis:
      pool:
        max-wait: 5000
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: y
  dubbo:
    server: true
    protocol:
      name: dubbo
      port: 20880
    registry: zookeeper://localhost:2181

mybatis:
  type-aliases-package: com.dubboss.seckillapi.entity
  mapper-locations: classpath:mapper/*.xml

