#dubbo:
 # application:
  #  name: seckill-consumer
  #scan:
  #  base-packages: com.dubboss.seckillprovider.mp
  #registry:
  #  address: zookeeper://localhost:2181
  #consumer:
  #  timeout: 30000
server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_seckill?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 1021
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    port: 6379
    host: 127.0.0.1
    timeout: 3
    # 最大连接数 total idle wait

  thymeleaf:
    suffix: .html
    enabled: true
    encoding: utf-8
    mode: HTML5
    servlet:
      content-type: text/html
    prefix: classpath:/templates/

  resources:
    static-locations: classpath:/static/
    add-mappings: true
    chain:
      html-application-cache: true
      cache: true
      enabled: true


  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: y
    listener:
      simple:
        concurrency: 10
        max-concurrency: 10
        prefetch: 1
        auto-startup: true
        default-requeue-rejected: true
        acknowledge-mode: manual
      direct:
        acknowledge-mode: manual
    template:
      retry:
        enabled: true
        max-attempts: 3
        multiplier: 1.0

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.dubboss.sk.entity
