dubbo:
  application:
    name: seckill-consumer
  scan:
    base-packages: com.dubboss.seckillprovider.mp
  registry:
    address: zookeeper://localhost:2181
  consumer:
    timeout: 30000
server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_seckill?useUnicode=true&characterEncoding=utf8
    username: root
    password: 1021
    driver-class-name: com.mysql.cj.jdbc.Driver
