server:
  port: 8084 #ÏîÄ¿¶Ë¿Ú

spring:
  application:
    name: seckill-goods
  dubbo:
    server: true
    registry: zookeeper://localhost:2181
    protocol:
      name: dubbo
      port: 20881
  datasource:
    url: jdbc:mysql://localhost:3306/db_seckill?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 1021
    driver-class-name: com.mysql.cj.jdbc.Driver